/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Operation = IDL.Variant({
  'subtraction' : IDL.Null,
  'division' : IDL.Null,
  'addition' : IDL.Null,
  'multiplication' : IDL.Null,
});
export const Problem = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Int,
  'operation' : Operation,
});
export const Time = IDL.Int;
export const Score = IDL.Record({
  'name' : IDL.Text,
  'numCorrect' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'generateProblem' : IDL.Func([], [Problem], []),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Operation = IDL.Variant({
    'subtraction' : IDL.Null,
    'division' : IDL.Null,
    'addition' : IDL.Null,
    'multiplication' : IDL.Null,
  });
  const Problem = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Int,
    'operation' : Operation,
  });
  const Time = IDL.Int;
  const Score = IDL.Record({
    'name' : IDL.Text,
    'numCorrect' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'generateProblem' : IDL.Func([], [Problem], []),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };